In [36]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from keras.models import Sequential
from sklearn.feature_extraction.text import CountVectorizer
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
from keras.callbacks import EarlyStopping
from LSTM_preprocess import *

data = pd.read_csv('reddit_train.csv', usecols=['comments', 'subreddits'])

In [37]:
data.subreddits.value_counts()

Music              3500
Overwatch          3500
nba                3500
europe             3500
baseball           3500
hockey             3500
AskReddit          3500
anime              3500
gameofthrones      3500
wow                3500
conspiracy         3500
leagueoflegends    3500
funny              3500
GlobalOffensive    3500
trees              3500
nfl                3500
movies             3500
soccer             3500
worldnews          3500
canada             3500
Name: subreddits, dtype: int64

In [38]:
num_of_categories = 3500
shuffled = data.reindex(np.random.permutation(data.index))
a = shuffled[shuffled['subreddits'] == 'AskReddit'][:num_of_categories]
b = shuffled[shuffled['subreddits'] == 'GlobalOffensive'][:num_of_categories]
c = shuffled[shuffled['subreddits'] == 'Music'][:num_of_categories]
d = shuffled[shuffled['subreddits'] == 'Overwatch'][:num_of_categories]
e = shuffled[shuffled['subreddits'] == 'anime'][:num_of_categories]
f = shuffled[shuffled['subreddits'] == 'baseball'][:num_of_categories]
g = shuffled[shuffled['subreddits'] == 'canada'][:num_of_categories]
h = shuffled[shuffled['subreddits'] == 'conspiracy'][:num_of_categories]
i = shuffled[shuffled['subreddits'] == 'europe'][:num_of_categories]
j = shuffled[shuffled['subreddits'] == 'funny'][:num_of_categories]
k = shuffled[shuffled['subreddits'] == 'gameofthrones'][:num_of_categories]
l = shuffled[shuffled['subreddits'] == 'hocky'][:num_of_categories]
m = shuffled[shuffled['subreddits'] == 'leagueoflegends'][:num_of_categories]
n = shuffled[shuffled['subreddits'] == 'movies'][:num_of_categories]
o = shuffled[shuffled['subreddits'] == 'nba'][:num_of_categories]
p = shuffled[shuffled['subreddits'] == 'nfl'][:num_of_categories]
q = shuffled[shuffled['subreddits'] == 'soccer'][:num_of_categories]
r = shuffled[shuffled['subreddits'] == 'trees'][:num_of_categories]
s = shuffled[shuffled['subreddits'] == 'worldnews'][:num_of_categories]
t = shuffled[shuffled['subreddits'] == 'wow'][:num_of_categories]

concated = pd.concat([a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t], ignore_index=True)
#Shuffle the dataset
concated = concated.reindex(np.random.permutation(concated.index))
concated['LABEL'] = 0

In [39]:
#One-hot encode the lab
concated.loc[concated['subreddits'] == 'AskReddit', 'LABEL'] = 0
concated.loc[concated['subreddits'] == 'GlobalOffensive', 'LABEL'] = 1
concated.loc[concated['subreddits'] == 'Music', 'LABEL'] = 2
concated.loc[concated['subreddits'] == 'Overwatch', 'LABEL'] = 3
concated.loc[concated['subreddits'] == 'anime', 'LABEL'] = 4
concated.loc[concated['subreddits'] == 'baseball', 'LABEL'] = 5
concated.loc[concated['subreddits'] == 'canada', 'LABEL'] = 6
concated.loc[concated['subreddits'] == 'conspiracy', 'LABEL'] = 7
concated.loc[concated['subreddits'] == 'europe', 'LABEL'] = 8
concated.loc[concated['subreddits'] == 'funny', 'LABEL'] = 9
concated.loc[concated['subreddits'] == 'gameofthrones', 'LABEL'] = 10
concated.loc[concated['subreddits'] == 'hocky', 'LABEL'] = 11
concated.loc[concated['subreddits'] == 'leagueoflegends', 'LABEL'] = 12
concated.loc[concated['subreddits'] == 'movies', 'LABEL'] = 13
concated.loc[concated['subreddits'] == 'nba', 'LABEL'] = 14
concated.loc[concated['subreddits'] == 'nfl', 'LABEL'] = 15
concated.loc[concated['subreddits'] == 'soccer', 'LABEL'] = 16
concated.loc[concated['subreddits'] == 'trees', 'LABEL'] = 17
concated.loc[concated['subreddits'] == 'worldnews', 'LABEL'] = 18
concated.loc[concated['subreddits'] == 'wow', 'LABEL'] = 19



print(concated['LABEL'][:10])
labels = to_categorical(concated['LABEL'], num_classes=20)
print(labels[:10])
if 'subreddits' in concated.keys():
    concated.drop(['subreddits'], axis=1)

3879      1
48288    14
18794     5
38245    10
48245    14
5200      1
15582     4
21398     6
27501     7
38543    12
Name: LABEL, dtype: int64
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [40]:
for i in range(len(concated["comments"])):
    concated["comments"][i] = preprocess_text(concated["comments"][i])

D:\PROGRAMS\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [41]:
n_most_common_words = 20000
max_len = 200
tokenizer = Tokenizer(num_words=n_most_common_words, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~0123456789', lower=True)
tokenizer.fit_on_texts(concated['comments'].values)
sequences = tokenizer.texts_to_sequences(concated['comments'].values)
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

X = pad_sequences(sequences, maxlen=max_len)

Found 56700 unique tokens.


In [42]:
X_train, X_test, y_train, y_test = train_test_split(X , labels, test_size=0.2, random_state=42)

In [43]:
epochs = 1000
emb_dim = 256
batch_size = 256
labels[:2]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [44]:
print((X_train.shape, y_train.shape, X_test.shape, y_test.shape))

((53200, 200), (53200, 20), (13300, 200), (13300, 20))


In [45]:
model = Sequential()
model.add(Embedding(n_most_common_words, emb_dim, input_length=X.shape[1]))
model.add(SpatialDropout1D(0.7))
model.add(LSTM(128, dropout=0.7, recurrent_dropout=0.7))
model.add(Dense(20, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
print(model.summary())
history = model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size,validation_split=0.25,callbacks=[EarlyStopping(monitor='val_loss',patience=7, min_delta=0.0001)])

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 200, 256)          5120000   
_________________________________________________________________
spatial_dropout1d_3 (Spatial (None, 200, 256)          0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 128)               197120    
_________________________________________________________________
dense_3 (Dense)              (None, 20)                2580      
Total params: 5,319,700
Trainable params: 5,319,700
Non-trainable params: 0
_________________________________________________________________
None


D:\PROGRAMS\Anaconda\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 39900 samples, validate on 13300 samples
Epoch 1/1000
39900/39900 [==============================] - ETA: 7:14 - loss: 2.9993 - acc: 0.046 - ETA: 6:51 - loss: 2.9931 - acc: 0.044 - ETA: 6:37 - loss: 2.9961 - acc: 0.044 - ETA: 6:40 - loss: 2.9960 - acc: 0.046 - ETA: 6:39 - loss: 2.9960 - acc: 0.047 - ETA: 6:42 - loss: 2.9979 - acc: 0.045 - ETA: 6:40 - loss: 2.9987 - acc: 0.046 - ETA: 6:40 - loss: 2.9989 - acc: 0.046 - ETA: 6:37 - loss: 2.9975 - acc: 0.051 - ETA: 6:31 - loss: 2.9981 - acc: 0.050 - ETA: 6:26 - loss: 2.9977 - acc: 0.051 - ETA: 6:21 - loss: 2.9973 - acc: 0.049 - ETA: 6:15 - loss: 2.9975 - acc: 0.049 - ETA: 6:12 - loss: 2.9968 - acc: 0.051 - ETA: 6:10 - loss: 2.9966 - acc: 0.052 - ETA: 6:08 - loss: 2.9965 - acc: 0.051 - ETA: 6:05 - loss: 2.9967 - acc: 0.051 - ETA: 6:02 - loss: 2.9964 - acc: 0.050 - ETA: 5:59 - loss: 2.9956 - acc: 0.051 - ETA: 5:56 - loss: 2.9950 - acc: 0.052 - ETA: 5:55 - loss: 2.9953 - acc: 0.052 - ETA: 5:54 - loss: 2.9950 - acc: 0.051 - ETA: 5:51 

39900/39900 [==============================] - ETA: 6:34 - loss: 2.8987 - acc: 0.093 - ETA: 6:29 - loss: 2.9047 - acc: 0.097 - ETA: 6:26 - loss: 2.9066 - acc: 0.102 - ETA: 6:24 - loss: 2.9027 - acc: 0.101 - ETA: 6:21 - loss: 2.9008 - acc: 0.100 - ETA: 6:18 - loss: 2.8986 - acc: 0.101 - ETA: 6:15 - loss: 2.8972 - acc: 0.099 - ETA: 6:12 - loss: 2.8973 - acc: 0.102 - ETA: 6:09 - loss: 2.8967 - acc: 0.100 - ETA: 6:06 - loss: 2.8944 - acc: 0.103 - ETA: 6:03 - loss: 2.8953 - acc: 0.104 - ETA: 6:01 - loss: 2.8948 - acc: 0.106 - ETA: 5:58 - loss: 2.8956 - acc: 0.106 - ETA: 5:55 - loss: 2.8951 - acc: 0.105 - ETA: 5:52 - loss: 2.8953 - acc: 0.106 - ETA: 5:50 - loss: 2.8951 - acc: 0.106 - ETA: 5:47 - loss: 2.8951 - acc: 0.106 - ETA: 5:44 - loss: 2.8951 - acc: 0.105 - ETA: 5:41 - loss: 2.8934 - acc: 0.107 - ETA: 5:38 - loss: 2.8930 - acc: 0.107 - ETA: 5:36 - loss: 2.8918 - acc: 0.107 - ETA: 5:33 - loss: 2.8901 - acc: 0.107 - ETA: 5:30 - loss: 2.8891 - acc: 0.108 - ETA: 5:28 - loss: 2.8888 - acc: 0

39900/39900 [==============================] - ETA: 6:36 - loss: 2.6171 - acc: 0.218 - ETA: 6:26 - loss: 2.5627 - acc: 0.222 - ETA: 6:24 - loss: 2.5509 - acc: 0.225 - ETA: 6:37 - loss: 2.5315 - acc: 0.222 - ETA: 6:33 - loss: 2.5147 - acc: 0.228 - ETA: 6:29 - loss: 2.5157 - acc: 0.225 - ETA: 6:28 - loss: 2.5225 - acc: 0.218 - ETA: 6:27 - loss: 2.5209 - acc: 0.220 - ETA: 6:30 - loss: 2.5142 - acc: 0.218 - ETA: 6:27 - loss: 2.5040 - acc: 0.218 - ETA: 6:26 - loss: 2.5068 - acc: 0.215 - ETA: 6:22 - loss: 2.5117 - acc: 0.213 - ETA: 6:19 - loss: 2.5156 - acc: 0.212 - ETA: 6:15 - loss: 2.5187 - acc: 0.210 - ETA: 6:11 - loss: 2.5181 - acc: 0.209 - ETA: 6:07 - loss: 2.5159 - acc: 0.210 - ETA: 6:03 - loss: 2.5159 - acc: 0.210 - ETA: 6:01 - loss: 2.5162 - acc: 0.210 - ETA: 5:59 - loss: 2.5160 - acc: 0.211 - ETA: 5:57 - loss: 2.5154 - acc: 0.212 - ETA: 5:55 - loss: 2.5165 - acc: 0.211 - ETA: 5:53 - loss: 2.5153 - acc: 0.210 - ETA: 5:52 - loss: 2.5130 - acc: 0.210 - ETA: 5:52 - loss: 2.5121 - acc: 0

39900/39900 [==============================] - ETA: 7:27 - loss: 2.1165 - acc: 0.320 - ETA: 7:25 - loss: 2.2305 - acc: 0.269 - ETA: 7:22 - loss: 2.2565 - acc: 0.273 - ETA: 7:14 - loss: 2.2642 - acc: 0.279 - ETA: 7:09 - loss: 2.2633 - acc: 0.278 - ETA: 7:08 - loss: 2.2730 - acc: 0.272 - ETA: 7:04 - loss: 2.2709 - acc: 0.275 - ETA: 7:01 - loss: 2.2708 - acc: 0.275 - ETA: 6:57 - loss: 2.2671 - acc: 0.278 - ETA: 6:53 - loss: 2.2712 - acc: 0.279 - ETA: 6:51 - loss: 2.2685 - acc: 0.279 - ETA: 6:48 - loss: 2.2599 - acc: 0.281 - ETA: 6:45 - loss: 2.2571 - acc: 0.280 - ETA: 6:43 - loss: 2.2597 - acc: 0.277 - ETA: 6:40 - loss: 2.2552 - acc: 0.281 - ETA: 6:36 - loss: 2.2595 - acc: 0.281 - ETA: 6:33 - loss: 2.2604 - acc: 0.279 - ETA: 6:30 - loss: 2.2591 - acc: 0.281 - ETA: 6:27 - loss: 2.2615 - acc: 0.280 - ETA: 6:23 - loss: 2.2577 - acc: 0.279 - ETA: 6:20 - loss: 2.2568 - acc: 0.278 - ETA: 6:18 - loss: 2.2601 - acc: 0.277 - ETA: 6:16 - loss: 2.2584 - acc: 0.278 - ETA: 6:12 - loss: 2.2614 - acc: 0

39900/39900 [==============================] - ETA: 8:37 - loss: 2.2024 - acc: 0.312 - ETA: 8:35 - loss: 2.1261 - acc: 0.324 - ETA: 8:22 - loss: 2.0902 - acc: 0.335 - ETA: 8:15 - loss: 2.0771 - acc: 0.336 - ETA: 8:08 - loss: 2.0751 - acc: 0.334 - ETA: 8:02 - loss: 2.0713 - acc: 0.337 - ETA: 8:01 - loss: 2.0676 - acc: 0.341 - ETA: 7:58 - loss: 2.0554 - acc: 0.341 - ETA: 7:53 - loss: 2.0382 - acc: 0.346 - ETA: 7:49 - loss: 2.0453 - acc: 0.347 - ETA: 7:46 - loss: 2.0539 - acc: 0.343 - ETA: 7:42 - loss: 2.0561 - acc: 0.344 - ETA: 7:38 - loss: 2.0499 - acc: 0.346 - ETA: 7:35 - loss: 2.0499 - acc: 0.344 - ETA: 7:32 - loss: 2.0592 - acc: 0.339 - ETA: 7:29 - loss: 2.0606 - acc: 0.338 - ETA: 7:26 - loss: 2.0561 - acc: 0.340 - ETA: 7:23 - loss: 2.0589 - acc: 0.340 - ETA: 7:19 - loss: 2.0619 - acc: 0.340 - ETA: 7:16 - loss: 2.0638 - acc: 0.340 - ETA: 7:11 - loss: 2.0613 - acc: 0.341 - ETA: 7:06 - loss: 2.0648 - acc: 0.341 - ETA: 7:01 - loss: 2.0675 - acc: 0.341 - ETA: 6:56 - loss: 2.0722 - acc: 0

39900/39900 [==============================] - ETA: 8:25 - loss: 1.9729 - acc: 0.382 - ETA: 8:17 - loss: 1.9156 - acc: 0.390 - ETA: 8:16 - loss: 1.9206 - acc: 0.391 - ETA: 8:12 - loss: 1.9541 - acc: 0.377 - ETA: 8:07 - loss: 1.9585 - acc: 0.385 - ETA: 8:04 - loss: 1.9475 - acc: 0.387 - ETA: 8:00 - loss: 1.9380 - acc: 0.388 - ETA: 7:55 - loss: 1.9511 - acc: 0.383 - ETA: 7:53 - loss: 1.9480 - acc: 0.385 - ETA: 7:45 - loss: 1.9308 - acc: 0.393 - ETA: 7:40 - loss: 1.9243 - acc: 0.396 - ETA: 7:38 - loss: 1.9313 - acc: 0.394 - ETA: 7:35 - loss: 1.9331 - acc: 0.393 - ETA: 7:31 - loss: 1.9277 - acc: 0.394 - ETA: 7:27 - loss: 1.9282 - acc: 0.397 - ETA: 7:24 - loss: 1.9304 - acc: 0.395 - ETA: 7:20 - loss: 1.9381 - acc: 0.392 - ETA: 7:16 - loss: 1.9315 - acc: 0.394 - ETA: 7:12 - loss: 1.9311 - acc: 0.393 - ETA: 7:08 - loss: 1.9346 - acc: 0.392 - ETA: 7:05 - loss: 1.9381 - acc: 0.391 - ETA: 7:01 - loss: 1.9390 - acc: 0.388 - ETA: 6:58 - loss: 1.9364 - acc: 0.389 - ETA: 6:54 - loss: 1.9343 - acc: 0

39900/39900 [==============================] - ETA: 8:00 - loss: 1.7738 - acc: 0.441 - ETA: 7:45 - loss: 1.7932 - acc: 0.414 - ETA: 7:30 - loss: 1.8524 - acc: 0.403 - ETA: 7:28 - loss: 1.8231 - acc: 0.417 - ETA: 7:23 - loss: 1.8076 - acc: 0.418 - ETA: 7:20 - loss: 1.8046 - acc: 0.425 - ETA: 7:19 - loss: 1.8030 - acc: 0.422 - ETA: 7:17 - loss: 1.7879 - acc: 0.435 - ETA: 7:14 - loss: 1.8005 - acc: 0.428 - ETA: 7:10 - loss: 1.8072 - acc: 0.425 - ETA: 7:07 - loss: 1.8082 - acc: 0.425 - ETA: 7:04 - loss: 1.8099 - acc: 0.424 - ETA: 7:00 - loss: 1.8104 - acc: 0.425 - ETA: 6:57 - loss: 1.8103 - acc: 0.426 - ETA: 6:53 - loss: 1.8108 - acc: 0.424 - ETA: 6:49 - loss: 1.8076 - acc: 0.427 - ETA: 6:45 - loss: 1.8050 - acc: 0.427 - ETA: 6:42 - loss: 1.8001 - acc: 0.426 - ETA: 6:39 - loss: 1.7911 - acc: 0.430 - ETA: 6:36 - loss: 1.7906 - acc: 0.431 - ETA: 6:32 - loss: 1.7860 - acc: 0.431 - ETA: 6:29 - loss: 1.7847 - acc: 0.433 - ETA: 6:27 - loss: 1.7867 - acc: 0.432 - ETA: 6:24 - loss: 1.7885 - acc: 0

39900/39900 [==============================] - ETA: 7:04 - loss: 1.7490 - acc: 0.476 - ETA: 7:06 - loss: 1.7607 - acc: 0.459 - ETA: 7:07 - loss: 1.7627 - acc: 0.463 - ETA: 7:06 - loss: 1.7687 - acc: 0.453 - ETA: 7:05 - loss: 1.7567 - acc: 0.461 - ETA: 6:59 - loss: 1.7460 - acc: 0.460 - ETA: 6:53 - loss: 1.7583 - acc: 0.458 - ETA: 6:46 - loss: 1.7600 - acc: 0.455 - ETA: 6:40 - loss: 1.7610 - acc: 0.457 - ETA: 6:36 - loss: 1.7643 - acc: 0.455 - ETA: 6:34 - loss: 1.7552 - acc: 0.456 - ETA: 6:31 - loss: 1.7437 - acc: 0.458 - ETA: 6:27 - loss: 1.7470 - acc: 0.458 - ETA: 6:23 - loss: 1.7385 - acc: 0.460 - ETA: 6:19 - loss: 1.7310 - acc: 0.465 - ETA: 6:15 - loss: 1.7263 - acc: 0.466 - ETA: 6:11 - loss: 1.7229 - acc: 0.467 - ETA: 6:08 - loss: 1.7139 - acc: 0.468 - ETA: 6:05 - loss: 1.7173 - acc: 0.468 - ETA: 6:03 - loss: 1.7139 - acc: 0.469 - ETA: 6:02 - loss: 1.7233 - acc: 0.465 - ETA: 6:00 - loss: 1.7190 - acc: 0.466 - ETA: 5:59 - loss: 1.7262 - acc: 0.464 - ETA: 5:57 - loss: 1.7229 - acc: 0

39900/39900 [==============================] - ETA: 7:08 - loss: 1.7834 - acc: 0.484 - ETA: 7:02 - loss: 1.6983 - acc: 0.496 - ETA: 7:07 - loss: 1.6642 - acc: 0.492 - ETA: 7:03 - loss: 1.6805 - acc: 0.476 - ETA: 6:59 - loss: 1.6853 - acc: 0.475 - ETA: 6:55 - loss: 1.6721 - acc: 0.481 - ETA: 6:51 - loss: 1.6664 - acc: 0.487 - ETA: 6:48 - loss: 1.6732 - acc: 0.489 - ETA: 6:47 - loss: 1.6751 - acc: 0.487 - ETA: 6:44 - loss: 1.6761 - acc: 0.485 - ETA: 6:41 - loss: 1.6788 - acc: 0.487 - ETA: 6:38 - loss: 1.6751 - acc: 0.487 - ETA: 6:35 - loss: 1.6703 - acc: 0.487 - ETA: 6:32 - loss: 1.6681 - acc: 0.493 - ETA: 6:29 - loss: 1.6720 - acc: 0.491 - ETA: 6:26 - loss: 1.6707 - acc: 0.490 - ETA: 6:23 - loss: 1.6687 - acc: 0.489 - ETA: 6:20 - loss: 1.6660 - acc: 0.489 - ETA: 6:17 - loss: 1.6628 - acc: 0.490 - ETA: 6:15 - loss: 1.6586 - acc: 0.491 - ETA: 6:12 - loss: 1.6604 - acc: 0.490 - ETA: 6:09 - loss: 1.6545 - acc: 0.491 - ETA: 6:06 - loss: 1.6537 - acc: 0.491 - ETA: 6:03 - loss: 1.6473 - acc: 0

39900/39900 [==============================] - ETA: 6:23 - loss: 1.6182 - acc: 0.503 - ETA: 6:20 - loss: 1.5893 - acc: 0.503 - ETA: 6:18 - loss: 1.6376 - acc: 0.502 - ETA: 6:17 - loss: 1.6227 - acc: 0.509 - ETA: 6:14 - loss: 1.6371 - acc: 0.512 - ETA: 6:12 - loss: 1.6008 - acc: 0.524 - ETA: 6:09 - loss: 1.5881 - acc: 0.522 - ETA: 6:06 - loss: 1.5700 - acc: 0.526 - ETA: 6:04 - loss: 1.5735 - acc: 0.526 - ETA: 6:01 - loss: 1.5575 - acc: 0.532 - ETA: 6:00 - loss: 1.5580 - acc: 0.531 - ETA: 5:58 - loss: 1.5596 - acc: 0.529 - ETA: 5:55 - loss: 1.5615 - acc: 0.528 - ETA: 5:53 - loss: 1.5693 - acc: 0.524 - ETA: 5:51 - loss: 1.5693 - acc: 0.524 - ETA: 5:48 - loss: 1.5654 - acc: 0.527 - ETA: 5:46 - loss: 1.5698 - acc: 0.527 - ETA: 5:44 - loss: 1.5670 - acc: 0.527 - ETA: 5:42 - loss: 1.5690 - acc: 0.527 - ETA: 5:39 - loss: 1.5702 - acc: 0.526 - ETA: 5:37 - loss: 1.5675 - acc: 0.527 - ETA: 5:34 - loss: 1.5725 - acc: 0.525 - ETA: 5:32 - loss: 1.5721 - acc: 0.525 - ETA: 5:29 - loss: 1.5688 - acc: 0

39900/39900 [==============================] - ETA: 6:32 - loss: 1.4015 - acc: 0.558 - ETA: 6:26 - loss: 1.4871 - acc: 0.546 - ETA: 6:21 - loss: 1.4517 - acc: 0.552 - ETA: 6:18 - loss: 1.4540 - acc: 0.554 - ETA: 6:14 - loss: 1.4470 - acc: 0.562 - ETA: 6:12 - loss: 1.4737 - acc: 0.549 - ETA: 6:10 - loss: 1.4917 - acc: 0.545 - ETA: 6:07 - loss: 1.4933 - acc: 0.544 - ETA: 6:05 - loss: 1.5118 - acc: 0.539 - ETA: 6:03 - loss: 1.5161 - acc: 0.539 - ETA: 6:00 - loss: 1.5105 - acc: 0.541 - ETA: 5:58 - loss: 1.5052 - acc: 0.541 - ETA: 5:55 - loss: 1.5025 - acc: 0.539 - ETA: 5:53 - loss: 1.4977 - acc: 0.542 - ETA: 5:51 - loss: 1.5005 - acc: 0.543 - ETA: 5:48 - loss: 1.5059 - acc: 0.540 - ETA: 5:46 - loss: 1.4957 - acc: 0.543 - ETA: 5:44 - loss: 1.4914 - acc: 0.544 - ETA: 5:42 - loss: 1.4971 - acc: 0.542 - ETA: 5:40 - loss: 1.4973 - acc: 0.540 - ETA: 5:37 - loss: 1.4947 - acc: 0.540 - ETA: 5:35 - loss: 1.4945 - acc: 0.541 - ETA: 5:33 - loss: 1.4959 - acc: 0.541 - ETA: 5:30 - loss: 1.4963 - acc: 0

39900/39900 [==============================] - ETA: 6:53 - loss: 1.4311 - acc: 0.558 - ETA: 6:46 - loss: 1.4034 - acc: 0.578 - ETA: 6:42 - loss: 1.4336 - acc: 0.574 - ETA: 6:37 - loss: 1.4513 - acc: 0.563 - ETA: 6:36 - loss: 1.4675 - acc: 0.553 - ETA: 6:30 - loss: 1.4536 - acc: 0.557 - ETA: 6:28 - loss: 1.4486 - acc: 0.555 - ETA: 6:26 - loss: 1.4454 - acc: 0.558 - ETA: 6:24 - loss: 1.4347 - acc: 0.559 - ETA: 6:21 - loss: 1.4345 - acc: 0.559 - ETA: 6:19 - loss: 1.4398 - acc: 0.555 - ETA: 6:16 - loss: 1.4334 - acc: 0.558 - ETA: 6:14 - loss: 1.4428 - acc: 0.553 - ETA: 6:11 - loss: 1.4409 - acc: 0.555 - ETA: 6:08 - loss: 1.4316 - acc: 0.558 - ETA: 6:05 - loss: 1.4355 - acc: 0.555 - ETA: 6:03 - loss: 1.4351 - acc: 0.557 - ETA: 6:03 - loss: 1.4295 - acc: 0.557 - ETA: 6:01 - loss: 1.4262 - acc: 0.559 - ETA: 5:59 - loss: 1.4158 - acc: 0.563 - ETA: 5:57 - loss: 1.4139 - acc: 0.563 - ETA: 5:54 - loss: 1.4145 - acc: 0.563 - ETA: 5:50 - loss: 1.4110 - acc: 0.563 - ETA: 5:47 - loss: 1.4157 - acc: 0

39900/39900 [==============================] - ETA: 7:13 - loss: 1.3708 - acc: 0.593 - ETA: 7:04 - loss: 1.4525 - acc: 0.560 - ETA: 6:55 - loss: 1.4182 - acc: 0.567 - ETA: 6:52 - loss: 1.4122 - acc: 0.574 - ETA: 6:44 - loss: 1.4286 - acc: 0.566 - ETA: 6:41 - loss: 1.4070 - acc: 0.571 - ETA: 6:39 - loss: 1.3977 - acc: 0.574 - ETA: 6:36 - loss: 1.4061 - acc: 0.573 - ETA: 6:34 - loss: 1.4095 - acc: 0.572 - ETA: 6:34 - loss: 1.4057 - acc: 0.576 - ETA: 6:31 - loss: 1.3941 - acc: 0.581 - ETA: 6:28 - loss: 1.3866 - acc: 0.584 - ETA: 6:26 - loss: 1.3790 - acc: 0.587 - ETA: 6:25 - loss: 1.3854 - acc: 0.587 - ETA: 6:22 - loss: 1.3901 - acc: 0.584 - ETA: 6:18 - loss: 1.3838 - acc: 0.585 - ETA: 6:15 - loss: 1.3844 - acc: 0.584 - ETA: 6:13 - loss: 1.3927 - acc: 0.585 - ETA: 6:09 - loss: 1.3893 - acc: 0.583 - ETA: 6:06 - loss: 1.3904 - acc: 0.583 - ETA: 6:03 - loss: 1.3854 - acc: 0.585 - ETA: 5:59 - loss: 1.3848 - acc: 0.584 - ETA: 5:57 - loss: 1.3801 - acc: 0.585 - ETA: 5:54 - loss: 1.3750 - acc: 0

39900/39900 [==============================] - ETA: 6:46 - loss: 1.3529 - acc: 0.597 - ETA: 6:40 - loss: 1.2852 - acc: 0.627 - ETA: 6:37 - loss: 1.2873 - acc: 0.615 - ETA: 6:33 - loss: 1.2769 - acc: 0.618 - ETA: 6:28 - loss: 1.2920 - acc: 0.618 - ETA: 6:25 - loss: 1.2739 - acc: 0.616 - ETA: 6:22 - loss: 1.2769 - acc: 0.616 - ETA: 6:18 - loss: 1.2865 - acc: 0.615 - ETA: 6:17 - loss: 1.2985 - acc: 0.605 - ETA: 6:14 - loss: 1.2992 - acc: 0.603 - ETA: 6:10 - loss: 1.3002 - acc: 0.601 - ETA: 6:08 - loss: 1.3073 - acc: 0.599 - ETA: 6:05 - loss: 1.3058 - acc: 0.602 - ETA: 6:05 - loss: 1.3237 - acc: 0.597 - ETA: 6:03 - loss: 1.3242 - acc: 0.595 - ETA: 6:00 - loss: 1.3260 - acc: 0.594 - ETA: 5:58 - loss: 1.3235 - acc: 0.594 - ETA: 5:55 - loss: 1.3286 - acc: 0.591 - ETA: 5:52 - loss: 1.3366 - acc: 0.590 - ETA: 5:50 - loss: 1.3325 - acc: 0.591 - ETA: 5:47 - loss: 1.3270 - acc: 0.592 - ETA: 5:44 - loss: 1.3296 - acc: 0.592 - ETA: 5:42 - loss: 1.3295 - acc: 0.593 - ETA: 5:39 - loss: 1.3279 - acc: 0

39900/39900 [==============================] - ETA: 6:29 - loss: 1.1251 - acc: 0.660 - ETA: 6:25 - loss: 1.1437 - acc: 0.642 - ETA: 6:24 - loss: 1.1348 - acc: 0.653 - ETA: 6:23 - loss: 1.1697 - acc: 0.649 - ETA: 6:22 - loss: 1.2181 - acc: 0.628 - ETA: 6:22 - loss: 1.2445 - acc: 0.619 - ETA: 6:23 - loss: 1.2705 - acc: 0.614 - ETA: 6:21 - loss: 1.2752 - acc: 0.612 - ETA: 6:18 - loss: 1.2939 - acc: 0.607 - ETA: 6:15 - loss: 1.2935 - acc: 0.606 - ETA: 6:13 - loss: 1.2903 - acc: 0.606 - ETA: 6:10 - loss: 1.2998 - acc: 0.602 - ETA: 6:07 - loss: 1.2871 - acc: 0.606 - ETA: 6:04 - loss: 1.2967 - acc: 0.603 - ETA: 6:01 - loss: 1.2939 - acc: 0.601 - ETA: 5:58 - loss: 1.2858 - acc: 0.603 - ETA: 5:55 - loss: 1.2888 - acc: 0.602 - ETA: 5:52 - loss: 1.2857 - acc: 0.605 - ETA: 5:50 - loss: 1.2865 - acc: 0.606 - ETA: 5:47 - loss: 1.2857 - acc: 0.607 - ETA: 5:45 - loss: 1.2921 - acc: 0.605 - ETA: 5:42 - loss: 1.2865 - acc: 0.607 - ETA: 5:41 - loss: 1.2921 - acc: 0.605 - ETA: 5:38 - loss: 1.2901 - acc: 0

39900/39900 [==============================] - ETA: 6:46 - loss: 1.2163 - acc: 0.617 - ETA: 6:37 - loss: 1.1717 - acc: 0.644 - ETA: 6:33 - loss: 1.1735 - acc: 0.649 - ETA: 6:28 - loss: 1.1899 - acc: 0.636 - ETA: 6:27 - loss: 1.2149 - acc: 0.628 - ETA: 6:24 - loss: 1.2270 - acc: 0.625 - ETA: 6:20 - loss: 1.2439 - acc: 0.628 - ETA: 6:18 - loss: 1.2404 - acc: 0.629 - ETA: 6:19 - loss: 1.2488 - acc: 0.625 - ETA: 6:18 - loss: 1.2609 - acc: 0.623 - ETA: 6:18 - loss: 1.2607 - acc: 0.621 - ETA: 6:16 - loss: 1.2546 - acc: 0.623 - ETA: 6:13 - loss: 1.2560 - acc: 0.622 - ETA: 6:10 - loss: 1.2615 - acc: 0.622 - ETA: 6:07 - loss: 1.2625 - acc: 0.621 - ETA: 6:04 - loss: 1.2619 - acc: 0.620 - ETA: 6:01 - loss: 1.2691 - acc: 0.619 - ETA: 6:00 - loss: 1.2750 - acc: 0.618 - ETA: 5:58 - loss: 1.2769 - acc: 0.615 - ETA: 5:55 - loss: 1.2798 - acc: 0.613 - ETA: 5:52 - loss: 1.2821 - acc: 0.611 - ETA: 5:49 - loss: 1.2827 - acc: 0.610 - ETA: 5:48 - loss: 1.2744 - acc: 0.613 - ETA: 5:46 - loss: 1.2713 - acc: 0

39900/39900 [==============================] - ETA: 6:55 - loss: 1.3535 - acc: 0.605 - ETA: 7:34 - loss: 1.2422 - acc: 0.615 - ETA: 7:56 - loss: 1.2757 - acc: 0.610 - ETA: 7:42 - loss: 1.2920 - acc: 0.603 - ETA: 7:25 - loss: 1.2631 - acc: 0.610 - ETA: 7:12 - loss: 1.2735 - acc: 0.612 - ETA: 7:01 - loss: 1.2740 - acc: 0.615 - ETA: 6:53 - loss: 1.2596 - acc: 0.618 - ETA: 6:46 - loss: 1.2627 - acc: 0.616 - ETA: 6:45 - loss: 1.2670 - acc: 0.614 - ETA: 6:48 - loss: 1.2594 - acc: 0.616 - ETA: 6:48 - loss: 1.2571 - acc: 0.614 - ETA: 6:41 - loss: 1.2477 - acc: 0.618 - ETA: 6:36 - loss: 1.2537 - acc: 0.615 - ETA: 6:31 - loss: 1.2489 - acc: 0.616 - ETA: 6:26 - loss: 1.2451 - acc: 0.617 - ETA: 6:23 - loss: 1.2467 - acc: 0.617 - ETA: 6:18 - loss: 1.2331 - acc: 0.620 - ETA: 6:13 - loss: 1.2323 - acc: 0.621 - ETA: 6:09 - loss: 1.2309 - acc: 0.621 - ETA: 6:05 - loss: 1.2359 - acc: 0.620 - ETA: 6:01 - loss: 1.2321 - acc: 0.621 - ETA: 5:57 - loss: 1.2307 - acc: 0.623 - ETA: 5:54 - loss: 1.2291 - acc: 0

39900/39900 [==============================] - ETA: 7:18 - loss: 1.2865 - acc: 0.589 - ETA: 7:24 - loss: 1.2298 - acc: 0.632 - ETA: 7:19 - loss: 1.2181 - acc: 0.628 - ETA: 7:13 - loss: 1.2227 - acc: 0.631 - ETA: 7:07 - loss: 1.2115 - acc: 0.636 - ETA: 7:02 - loss: 1.2204 - acc: 0.635 - ETA: 6:58 - loss: 1.2096 - acc: 0.636 - ETA: 6:55 - loss: 1.1894 - acc: 0.643 - ETA: 6:52 - loss: 1.1932 - acc: 0.641 - ETA: 6:50 - loss: 1.1959 - acc: 0.639 - ETA: 6:48 - loss: 1.1963 - acc: 0.641 - ETA: 6:45 - loss: 1.1922 - acc: 0.643 - ETA: 6:42 - loss: 1.1862 - acc: 0.647 - ETA: 6:40 - loss: 1.1818 - acc: 0.649 - ETA: 6:37 - loss: 1.1818 - acc: 0.649 - ETA: 6:35 - loss: 1.1856 - acc: 0.648 - ETA: 6:32 - loss: 1.1903 - acc: 0.647 - ETA: 6:30 - loss: 1.1858 - acc: 0.648 - ETA: 6:28 - loss: 1.1913 - acc: 0.647 - ETA: 6:26 - loss: 1.1841 - acc: 0.650 - ETA: 6:23 - loss: 1.1866 - acc: 0.649 - ETA: 6:21 - loss: 1.1832 - acc: 0.650 - ETA: 6:19 - loss: 1.1844 - acc: 0.652 - ETA: 6:19 - loss: 1.1842 - acc: 0

39900/39900 [==============================] - ETA: 6:35 - loss: 1.1302 - acc: 0.652 - ETA: 6:45 - loss: 1.2073 - acc: 0.632 - ETA: 6:41 - loss: 1.1512 - acc: 0.641 - ETA: 6:36 - loss: 1.1360 - acc: 0.643 - ETA: 6:33 - loss: 1.1210 - acc: 0.650 - ETA: 6:34 - loss: 1.1067 - acc: 0.651 - ETA: 6:35 - loss: 1.1345 - acc: 0.644 - ETA: 6:36 - loss: 1.1321 - acc: 0.645 - ETA: 6:36 - loss: 1.1362 - acc: 0.650 - ETA: 6:35 - loss: 1.1396 - acc: 0.651 - ETA: 6:32 - loss: 1.1395 - acc: 0.653 - ETA: 6:30 - loss: 1.1255 - acc: 0.657 - ETA: 6:28 - loss: 1.1281 - acc: 0.656 - ETA: 6:26 - loss: 1.1277 - acc: 0.657 - ETA: 6:24 - loss: 1.1260 - acc: 0.657 - ETA: 6:22 - loss: 1.1293 - acc: 0.656 - ETA: 6:19 - loss: 1.1406 - acc: 0.653 - ETA: 6:17 - loss: 1.1390 - acc: 0.654 - ETA: 6:14 - loss: 1.1481 - acc: 0.651 - ETA: 6:11 - loss: 1.1508 - acc: 0.651 - ETA: 6:08 - loss: 1.1478 - acc: 0.652 - ETA: 6:06 - loss: 1.1537 - acc: 0.649 - ETA: 6:03 - loss: 1.1606 - acc: 0.646 - ETA: 6:00 - loss: 1.1650 - acc: 0

39900/39900 [==============================] - ETA: 6:24 - loss: 1.0476 - acc: 0.648 - ETA: 6:25 - loss: 1.0957 - acc: 0.648 - ETA: 6:22 - loss: 1.1345 - acc: 0.653 - ETA: 6:21 - loss: 1.1436 - acc: 0.650 - ETA: 6:19 - loss: 1.1613 - acc: 0.643 - ETA: 6:16 - loss: 1.1293 - acc: 0.655 - ETA: 6:11 - loss: 1.1494 - acc: 0.650 - ETA: 6:14 - loss: 1.1331 - acc: 0.653 - ETA: 6:12 - loss: 1.1217 - acc: 0.653 - ETA: 6:09 - loss: 1.1112 - acc: 0.654 - ETA: 6:09 - loss: 1.1059 - acc: 0.656 - ETA: 6:06 - loss: 1.1124 - acc: 0.656 - ETA: 6:04 - loss: 1.1283 - acc: 0.652 - ETA: 6:01 - loss: 1.1387 - acc: 0.648 - ETA: 5:59 - loss: 1.1325 - acc: 0.651 - ETA: 5:56 - loss: 1.1269 - acc: 0.652 - ETA: 5:53 - loss: 1.1293 - acc: 0.652 - ETA: 5:51 - loss: 1.1283 - acc: 0.653 - ETA: 5:49 - loss: 1.1338 - acc: 0.653 - ETA: 5:46 - loss: 1.1374 - acc: 0.653 - ETA: 5:43 - loss: 1.1354 - acc: 0.654 - ETA: 5:41 - loss: 1.1358 - acc: 0.654 - ETA: 5:38 - loss: 1.1334 - acc: 0.655 - ETA: 5:35 - loss: 1.1352 - acc: 0

In [12]:
# read the test set
test_data = pd.read_csv('reddit_test.csv', usecols=['id','comments'])
for i in range(len(test_data["comments"])):
    test_data["comments"][i] = preprocess_text(test_data["comments"][i])

test_sequences = tokenizer.texts_to_sequences(test_data['comments'].values)
max_len = 200
test_X = pad_sequences(test_sequences, maxlen=max_len)
prediction = model.predict(test_X)

D:\PROGRAMS\Anaconda\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [20]:
print((prediction[2]))

[1.6603477e-03 1.6893185e-04 6.4626784e-04 6.1592192e-04 9.3740296e-01
 2.2477540e-04 1.1542122e-04 3.2671602e-04 4.6760516e-04 2.7686174e-03
 4.8264828e-02 6.9848693e-06 6.4075837e-05 5.4430682e-03 1.0488226e-04
 7.1348477e-05 7.8151104e-05 4.5965239e-04 6.2732463e-04 4.8216953e-04]


In [ ]:
class_dict ={
    0:'AskReddit',
    1:'GlobalOffensive',
    2:'Music',
    3:'Overwatch',
    4:'anime',
    5:'baseball',
    6:'canada',
    7:'conspiracy',
    8:'europe',
    9:'funny',
    10:'gameofthrones',
    11:'hocky',
    12:'leagueoflegends',
    13:'movies',
    14:'nba', 
    15:'nfl', 
    16:'soccer',
    17:'trees',
    18:'worldnews',
    19:'wow'}

In [ ]:
# save the model to local
import pickle
filename = 'finalized_model.sav'
pickle.dump(model, open(filename, 'wb'))

# some time later...
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, Y_test)
print(result)